app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/prueba', function () {
    return view('pages.prueba');
});

Route::get('about', [
    'as' => 'about',
    'uses' => 'PagesController@getAbout'
]);


Route::get('contact', 'PagesController@getContact')->name('contact');
/*
Route::get('contact', ['as' => 'contact', function () {
    return view('pages.contact');
}]);
*/
Route::get('basicrouting',function(){
  return 'THIS IS BASIC ROUTING';
  //return view('welcome');
});
Route::get('user/{id}',function($id){
  //$user = User::find($id);
  return $id;
  //return view('welcome');
});
Route::get('user/{id}/album/{aid}',function($id,$aid){
  //$user = User::find($id);
  return $id.' '.$aid;
  //return view('welcome');
});
Route::get('album/{aid?}',function($aid=null){
  //$user = User::find($id);
  return $aid;
  //return view('welcome');
});
Route::post('someurl',function(){
  //return 'THIS IS BASIC ROUTING';
  //return view('welcome');
  //no logic here
});
//http verbs
Route::match(['get','post','delete'],'matchrouting',function(){
  return 'matchrouting';
  //return view('welcome');
});
Route::any('anyroute',function(){
  return 'anyroute';
});

Route::resource('product', 'ProductController');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamps=false;
    protected $table = 'products';

    protected $fillable =  ['name', 'price'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;


use App\Http\Controllers\Controller;

class PagesController extends Controller
{
  public function getAbout(){
    $companyName = "LDAW";
    $users = array("hugo","paco","luis");
    return view('pages.about')
    ->with("name", $companyName)
    ->with("users", $users);
  }
  public function getContact(){
    return view('pages.contact');
  }
  public function register(){
    echo "User";
  }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;

class ProductController extends Controller
{
    public function index(){
      $products = Product::all();
      //return $products;
      return view('products.index')->with('products',$products);
    }
    public function create(){
      return view('products.create');
    }

    public function store(Request $request){
    // dd($request);
      /*$product = new Product;
      $product->name= $request->name;
      $product->price= $request->price;
      $product->save();
      */
      $inputs= $request->all();
      $product= Product::firstorCreate($inputs);

      //return redirect()->route('product.index');
      return redirect()->action('ProductController@index');
    }
    public function show($id){
      $product= Product::where('id','=',$id)->first();
      //return $product;
      return view('products.show')->with('product',$product);
    }
    public function destroy($id){
      //Product::destroy($id);
      $product=Product::find($id)->delete();
      return redirect()->route('product.index');
    }

    public function edit($id)
    {
      $product= Product::findOrFail($id);
      return view('products.edit',compact('product',$product));
    }
    public function update(Request $request, $id)
    {
      $product= Product::findOrFail($id);
      $product->name =$request->name;
      $product->price =$request->price;
      $product->save();
      return redirect()->route('product.index');
    }
}

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>@yield('title')</title>
    <!-- CSS  -->
    <link href="{{ asset('/css/semantic.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/css/container.min.css') }}" rel="stylesheet">
    <script src="{{ asset('/js/semantic.min.js') }}"></script>
    <!-- Compiled and minified CSS -->

  </head>
  <body>

    @include('layouts.menu')
      <div class="">
        @yield('content')

      </div>


  </body>
</html>

resources/views/layouts/menu.blade.php
<div class="ui secondary vertical pointing menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
</div>

resources/views/pages/about.blade.php
@extends('layouts.layout')


@section('title')
  About
@stop

@section('content')
<button class="ui primary button">
  Button
</button>
<div class="ui black button" tabindex="0">
  Focusable
</div>

<div class="ui four column doubling stackable grid container">
  <div class="column">
    <p>h</p>
    <p></p>
  </div>
  <div class="column">
    <p>g</p>
    <p></p>
  </div>
  <div class="column">
    <p>f</p>
    <p></p>
  </div>
  <div class="column">
    <p>l</p>
    <p></p>
  </div>
</div>
@stop

resources/views/pages/contact.blade.php
@extends('layouts.layout')
@section('title')
  Contact
@stop

@section('content')
<br><br>
<h1>Contact</h1>

<input type="text" name="nombre" placeholder="nombre de producto">
<input type="text" name="precio" placeholder="precio de producto">



<br><br>
@stop

resources/views/products/create.blade.php
@extends('layouts.layout')


@section('title')
  Create new product
@stop

@section('content')
<br><br>
<h1>Create Product</h1>
<div>
  <form action="{{route('product.store')}}" method="POST" >
    <div class="form-group">
      <input type="text" name="name">
      <input type="number" name="price">
      <button type="submit">Submit</button>
    </div>
  </form>
</div>

<br><br>
@stop

resources/views/products/edit.blade.php
@extends('layouts.layout')


@section('title')
  Edit product
@stop

@section('content')
<br><br>
<form action="{{route('product.update',$product->id)}}" method="POST" >
  <div class="form-group">
    <input type="text" name="name" value="{{$product->name}}">
    <input type="number" name="price" value="{{$product->price}}">
    <button type="submit">Edit</button>
  </div>

  {{method_field('PATCH')}}

</form>
@stop

resources/views/products/index.blade.php
@extends("layouts.layout")
@section("title")
  All products
@stop
@section("content")
  @foreach ($products as $product)
    <h1>{{$product->name}}</h1>
    <h3>{{$product->price}}</h3>
    <br/>
  @endforeach
  <a href="{{url('basicrouting')}}">Basic routing</a>
  <a href="{{route('product.create')}}">Create</a>

@stop

resources/views/products/show.blade.php
@extends('layouts.layout')


@section('title')
  Show product
@stop

@section('content')
<br><br>
<form action="{{route('product.destroy',$product->id)}}" method="POST" >


  <h1>{{$product->name}}</h1>
  <h3>{{$product->price}}</h3>

  <a href="{{route('product.edit', $product->id)}}">Edit</a>
  <input type="submit" value="delete">

  {{method_field('DELETE')}}

</form>
@stop